### ISSUE TITLE
Attempting to open "karel" folder gives error message

### ISSUE THREAD

**Issue by alexschrod** [wijnen/pydink#4]
File->Open, pick "karel" directory within pydink directory in dialog, get error message:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gui.py", line 770, in response
    widget.hide()
TypeError: 'bool' object is not callable
```

Quick additional testing reveals it actually happens when choosing any directory.

**Comment by wijnen** [comment]
Well that took incredibly long, but I finally looked into it.  It was more complicated than I thought it would be, but it's fixed now.  Thanks again for reporting it.

By the way, adding it on the commandline is now done as:
```
./pde.py --root karel
```
